
name: green-recorder
version: '3.0.4'
summary: Simple screen recorder for Linux desktop. Supports Xorg & Wayland.
description: |
  Simple and easy screen recorder for Linux desktop. Supports Xorg & Wayland.

grade: stable
confinement: strict

parts:
  my-part:
    plugin: nil
